---
# tasks file for httpdserver
- name: install apache2
  package:
    name: apache2
    state: present
- name: copy code
  copy:
    src: ./index.html
    dest: "/var/www/html/index.html"
- name: start apache2
  service:
    name: apache2
    state: started
