---
# tasks file for httpdserver
- name: install httpd
  package:
    name: httpd
    state: present
- name: copy code
  copy:
    src: ./index.html
    dest: "/var/www/html/index.html"
- name: start httpd
  service:
    name: httpd
    state: started
