name: deployAnsible

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo
      uses: actions/checkout@v3

    - name: print current working directory
      run: |
        pwd
    - name: list directory contents
      run: |
        ls -lart
    - name: list directory contents of directory one level up
      run: |
        cd ..
        ls -lart
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        options: |
          --verbose
