name: deployAnsible

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo
      uses: actions/checkout@v3

    - name: print current working directory
      run: |
        pwd
    - name: list directory contents
      run: |
        ls -lart
    - name: list directory contents of directory one level up
      run: |
        cd ..
        ls -lart
    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: ansible/deploy-ec2.yml
        options: |
          --verbose
          --extra-vars "access_key=$secrets.access_key secret_key=$secrets.secret_key region=$secrets.region"
