name: deployAnsibleStandAloneAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout my repo
      uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{secrets.REPO_TOKEN}}
    - name: print current working directory
      run: |
        pwd
    - name: list directory contents
      run: |
        ls -lart
    - name: list directory contents of directory one level up
      run: |
        cd ..
        ls -lart
      - name: Setup SSH
        shell: bash
        run: |
         eval `ssh-agent -s`
         mkdir -p /home/runner/.ssh/
         touch /home/runner/.ssh/id_rsa
         echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa
         chmod 700 /home/runner/.ssh/id_rsa
         ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts
      - name: Run ansible script
        shell: bash
        run: |
          service ssh status
          cd infrastructure/ansible
          cat setup-prod.yml
          ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa -u ${{secrets.ANSIBLE_DEPLOY_USER}} ansible/deploy.yml


